changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Security and reliability
      labels:
        - security
        - reliability
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
