[mypy]
python_version = 3.13
explicit_package_bases = True
ignore_missing_imports = True
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
pretty = True
